---
- hosts: all
  gather_facts: false
 
  tasks:
     - name: debug loop
       debug: msg="key={{item.key}} value={{item.value}}"
       with_items:
         - {key: "223" value: 234}
         - {key: "243" value: 234}
         
    
    
      
